### ISSUE TITLE
Can't find league process in windows if run from Windows Subsystem for Linux

### ISSUE THREAD

**Issue by alexsherman** [Pupix/lcu-connector#9]
Currently, if you're working within WSL and your League of Legends client is installed as a normal Windows program, `WMIC PROCESS WHERE name='LeagueClientUx.exe' GET commandline` will never find the program. Instead, you would have to do something like this: 

` command = "echo WMIC PROCESS WHERE \\\"name=\\'LeagueClientUx.exe\\'\\\" GET commandline | powershell.exe"`

In addition, `let lockfile_path = path.join(this._dirPath, 'lockfile');` doesn't work because _dirPath will be the windows path which needs to be referred to using the virtual mount. You can do something like: ` cp.exec("echo wsl wslpath \\\'" + lockfile_path + "\\\' | powershell.exe" ...` and process stdout to get the actual path.

As far as actually detecting if someone is on WSL, I think best option is probably something like:
`const IS_WSL = process.platform === 'linux' && process.env.PATH.indexOf("/mnt/c/Windows/System32") > -1;`

Probably not a very high priority issue and it would add some complexity to what is a very nice and simple file.

**Comment by Pupix** [comment]
My understanding is that WSL doesn't have an UI. Are you launching League from it? How does that work? It uses Wine inside WSL or escapes and just launches the straight windows .exe ?

**Comment by alexsherman** [comment]
My use case is that I prefer to do all dev work in WSL, which as you noted
as support for GUI outside of a shell, but I install and launch programs
like League from inside Windows. Because the subsystem can access any
Windows files by using /mnt/ this is usually not a problem, but it causes a
little bit of a headache in scenarios like this.

This would only mostly useful during development for anyone who wants to
develop an app using lcu-connector using WSL.

**Comment by Pupix** [comment]
Oh I see. So League is running on the windows host while your node is launched under WSL. Can't promise anything on this, I'll look into it during the weekend.

**Comment by Ranciovich** [comment]
Can you help me, when opening Rift Explorer, I get "Waiting for League to start ..." and it doesn't open League of Legends, Help please :c
